{% set version = "1.5-9.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-locfit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/locfit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/locfit/locfit_{{ version }}.tar.gz
  sha256: d9d3665c5f3d49f698fb4675daf40a0550601e86db3dc00f296413ceb1099ced

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-lattice
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-lattice

test:
  commands:
    - $R -e "library('locfit')"  # [not win]
    - "\"%R%\" -e \"library('locfit')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=locfit
  license: GPL-2
  summary: Local regression, likelihood and density estimation.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
