{% set version = "1.5-9.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-locfit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/locfit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/locfit/locfit_{{ version }}.tar.gz
  sha256: fa31b9d407f3557a6fcb7105cbd7b16a32a6fb868a7c60bc38a3e33cb7a39343

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  ## ignore workaround patching for https://github.com/conda-forge/r-base-feedstock/issues/349
  ignore_prefix_files:
    - lib/R/etc/Makeconf

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-lattice
  run:
    - r-base
    - r-lattice

test:
  commands:
    - $R -e "library('locfit')"           # [not win]
    - "\"%R%\" -e \"library('locfit')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=locfit
  license: GPL-2.0-or-later
  summary: Local regression, likelihood and density estimation.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
