{% set version = '1.5-9.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-locfit
  version: {{ version|replace("-", "_") }}

source:
  fn: locfit_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/locfit_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/locfit/locfit_{{ version }}.tar.gz
  sha256: f524148fdb29aac3a178618f88718d3d4ac91283014091aa11a01f1c70cd4e51

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-lattice

  run:
    - r-base
    - r-lattice

test:
  commands:
    - $R -e "library('locfit')"  # [not win]
    - "\"%R%\" -e \"library('locfit')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=locfit
  license: GPL (>= 2)
  summary: Local regression, likelihood and density estimation.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
