travis:
  secure:
    BINSTAR_TOKEN: KwFiPxyumI9C05DUsH3eJaYM1o/dbBUUiCgt8jmXmtuiIA7lic+oT9e86SepGId/bgpilXGyhIBl5WrIvseMxCXFE55nbIsXBk1FQO+v1mfx8Dr1NSGrdxSeM73nymo7mfO9o33Dip5uIevycQR5Kl8UJOAbemHzcfBIi45EmX7C516iD/MdPt/Il5AniS4spXYJg7O843mL5V7ZRrLtyr7cT1HMdc/D/5YEUiXcK5CzPJopxxzkz/lW/+BESpqRaXkA55pTFh6DK0ZmOsEbNuUU8HjaswGUkmJ0m0/Cydsjgse0+PHySHkwXB+gIsO8n+nk3f4Isgn/+c/j1VWajqbXZjJTrG78IBLaICRsDJU1Y1Y5u4S0Cu9hKA0nq7DykqXA0kbg5La+WTpcwjbeY+8X+2Vkn8p2TQvSdywWR0Ep0R7TGZXx6WvN3rjh98SmgJbEAmWj5548Ftq0ZgnbNSbh6/1fy5khCXG8WPRp1OaMSf7Czc9LZgTrNgGuxg2H76DgxEuBWgMb0CG/ctRN6NCOtDhTB942klyELPJbtY35vZVDSeuhIZt0omI1kezZ94n8XDzU/59lUXR9ZVtoA3JCTMdNEhmcHDgJb8ZXJvin1u8jmX81UkUgkjLaagWjpcxdpFAit7HTcw8CxAzIjZXhr547dKuSm+xfkJj8Wfk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
